volumes:
    langgraph-data:
        driver: local
services:
    langgraph-api:
        image: ${IMAGE_NAME}
        ports:
            - "2024:8000"
        env_file:
            - .env
        environment:
            REDIS_URI: ${REDIS_URI}
            LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
            POSTGRES_URI: ${POSTGRES_URI}